# Generated by Django 2.2.5 on 2019-09-19 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorname',
            fields=[
                ('color_id', models.UUIDField(blank=True, default=uuid.UUID('60e188ac-5d31-4d82-a033-a691981ca66f'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('colorname', models.CharField(max_length=50, verbose_name='Renk ismi')),
            ],
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d90de60e-4cab-4b1d-a965-2a1486a3caa4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
