# Generated by Django 2.2.5 on 2019-09-19 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0002_auto_20190919_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('size_id', models.UUIDField(blank=True, default=uuid.UUID('b5e97bea-8f97-41c0-b3bf-2abf55c616ae'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50)),
                ('size', models.CharField(max_length=50, verbose_name='Ölçüler')),
            ],
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('96eaafdf-3bfc-44ca-868b-55e4f57a915d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('78d2d934-45b4-41a8-b65d-a09266330608'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
