# Generated by Django 2.2.5 on 2019-09-19 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0003_auto_20190919_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('color2_id', models.UUIDField(blank=True, default=uuid.UUID('dbebd61f-34d2-47e5-9d5b-b1f9d7879d56'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('exp', models.CharField(max_length=100, verbose_name='Renk açıklama (Hangi model ve hangi boyutiçin kaçıncı renk?)')),
                ('model', models.CharField(choices=[('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Kategori')),
                ('backimage', models.ImageField(upload_to='', verbose_name='Arka resim')),
                ('frontimage', models.ImageField(upload_to='', verbose_name='Ön resim')),
            ],
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('fab167c6-16d8-46ce-aaab-9bcc3541f632'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7eabcd9e-9e87-42df-a199-0b1b22f2fac0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6fb4ec1a-8f29-4c07-a327-1edf03f803be'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('price_id', models.UUIDField(blank=True, default=uuid.UUID('34c65fc1-b8ee-4f27-a5ca-75b600ed0885'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(choices=[('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Model')),
                ('price50_100', models.IntegerField(verbose_name='Fiyat (50-100 adet için)')),
                ('price100_200', models.IntegerField(verbose_name='Fiyat (100-200 adet için)')),
                ('price200_500', models.IntegerField(verbose_name='Fiyat (200-500 adet için)')),
                ('price500_1000', models.IntegerField(verbose_name='Fiyat (500-1000 adet için)')),
                ('price1000_2000', models.IntegerField(verbose_name='Fiyat (1000-5000 adet için)')),
                ('price2000_5000', models.IntegerField(verbose_name='Fiyat (1000-5000 adet için)')),
                ('priceDesignService', models.IntegerField(verbose_name='Tasarim hizmet bedeli')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takvim2020.size', verbose_name='Boyut')),
            ],
        ),
    ]
