# Generated by Django 2.2.5 on 2019-09-19 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takvim2020', '0004_auto_20190919_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Açıklama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e819d025-5e43-4ed1-b326-5c55180d0740'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('56359928-b08c-4df0-bc3a-ca0b9a805c87'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6cade09a-70de-469b-b078-cc164bca10e0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ccec1a90-bb12-41ee-a69d-51a514b5c0ee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ac1a96a8-c18a-484c-8778-c76c4e7ca2f2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, verbose_name='Isim soyisim')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='adres')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefon')),
                ('comName', models.CharField(blank=True, max_length=100, verbose_name='Sirket ismi')),
                ('isActive', models.IntegerField(choices=[(0, 'Inaktif'), (1, 'Aktif')], default=0)),
                ('dateofJoin', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MainUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gemici3',
            fields=[
                ('product_id', models.UUIDField(blank=True, default=uuid.UUID('8b6afceb-49b2-421c-9e10-4608261ee9a7'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='GEMİCİ 3 Spiral', max_length=50)),
                ('category', models.CharField(choices=[('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('s1color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenkFotograf1Size', to='takvim2020.color', verbose_name='Renk - Fotoğraf 1. Size')),
                ('s1color2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenkFotograf1Size2', to='takvim2020.color', verbose_name='2. Renk- Fotoğraf 1. Size')),
                ('s1price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat1Size', to='takvim2020.price', verbose_name='Fiyat 1. Size')),
                ('s1size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olcu1Size', to='takvim2020.size', verbose_name='Ölçü 1. Size')),
                ('s2color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenkFotograf2Size', to='takvim2020.color', verbose_name='Renk - Fotoğraf 2. Size')),
                ('s2color2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenkFotograf2Size2', to='takvim2020.color', verbose_name='2. Renk - Fotoğraf 2. Size')),
                ('s2price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat2Size', to='takvim2020.price', verbose_name='Fiyat 2. Size')),
                ('s2size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olcu2Size', to='takvim2020.size', verbose_name='Ölçü 2. Size')),
                ('s3color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenkFotograf3Size', to='takvim2020.color', verbose_name='Renk - Fotoğraf 3. Size')),
                ('s3color2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenkFotograf3Size2', to='takvim2020.color', verbose_name='2. Renk - Fotoğraf 3. Size')),
                ('s3price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat3Size', to='takvim2020.price', verbose_name='Fiyat 3. Size')),
                ('s3size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Olcu3Size', to='takvim2020.size', verbose_name='Ölçü 3. Size')),
            ],
        ),
    ]
