# Generated by Django 2.2.5 on 2019-09-20 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0005_auto_20190919_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='exp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Açıklama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9cceb9da-943e-443c-885c-ea92e214647b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7649d9f3-01b0-4c03-b12c-9af456b9d4a6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7739c7c5-28d5-49c4-9a1b-12b3803e336e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='s1price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat1Fiyat', to='takvim2020.price', verbose_name='Fiyat 1. Fiyat'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='s2price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat2Fiyat', to='takvim2020.price', verbose_name='Fiyat 2. Fiyat'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='s3price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat3Fiyat', to='takvim2020.price', verbose_name='Fiyat 3. Fiyat'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('adb1a877-e095-4fa6-91ca-84e9f989a49a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('669a0ddc-717f-4657-a422-7d459a631a31'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('251dfe85-224c-4951-97b1-cccac5760e70'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
