# Generated by Django 2.2.5 on 2019-09-20 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0009_auto_20190920_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f5629893-c226-4ab5-80be-4db2b27d135f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ace25a93-d8ef-400b-bf97-88d28c40d056'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c0105fe3-8cef-4837-8986-f8479f5812d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('12d70d01-4e31-4779-bbf9-d1ca6f8e78f8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('239d120e-473c-430e-968d-da25b03c74f4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('masaustu', 'MASAUSTU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('cfdc0ef2-11d3-426a-b1be-18dd0b264118'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
