# Generated by Django 2.2.5 on 2019-09-20 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0011_auto_20190920_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d990b2a6-f265-43c6-89ba-c6ebb16e4951'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('765bc512-f07c-4f42-8215-99b2014889ef'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8a37c7b2-5a1c-4680-8c95-b45a9e3395bf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6ecae45e-11dc-48e1-aedd-454eb7bbf516'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f1b80f32-b16c-447e-af08-dc7f74d5dbf8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('678c80ae-d631-4c82-ba78-a2977781dab2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
