# Generated by Django 2.2.5 on 2019-09-21 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0012_auto_20190920_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('781f8a19-1598-458a-b94f-d9380749b9d3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('fa9b8a17-11a3-47a1-963b-8eee14c9a8d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('28fd8233-e1a4-4d18-8098-dd119f4ba880'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6fae93c9-136a-4a9c-859b-079bc5950651'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c962485e-f170-48d7-a628-1cb4f9aedb89'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0640d6e4-d449-4b28-bc69-0a5be735dc75'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
