# Generated by Django 2.2.5 on 2019-09-21 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0014_auto_20190921_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemici3',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='gemici3',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='gemici3',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat1Fiyat', to='takvim2020.price', verbose_name='Fiyat 1. Fiyat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('86c9832c-f718-41c5-bfd6-8f75101bc42b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2db901f3-08c3-478f-895d-2795dc87c374'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e171cc27-227d-42c1-b5da-b138c2c34e82'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d3e006ed-a964-48b0-a903-184c15f29f20'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b7e30606-62fa-4536-8378-bd6d08664442'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0b37d4e7-2a69-466a-bdce-197d45c75fdf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
