# Generated by Django 2.2.5 on 2019-09-21 18:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0022_auto_20190921_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemici3',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='gemici3',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='gemici3',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fiyat2Fiyat', to='takvim2020.price', verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0573c08e-27d4-42ff-9ec7-4531e7339023'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('166886f9-2e42-4650-81f0-594f9e855b80'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0394a7d1-879b-4588-a34c-4ae704cd429f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('afbfcb63-6a43-4aa5-aff1-fa47de35b447'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('378a1bea-1a53-4918-bc7a-1c8fa0149073'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('380f8caf-39e7-418e-b5b0-e08e2e0c0eea'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
