# Generated by Django 2.2.5 on 2019-09-23 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0027_auto_20190923_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e537caa6-729d-490b-a151-0e53b70cee54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('67e9b767-11ad-4517-be25-e35ce7ebe8ca'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a1f5d9e9-9e6c-4be7-bb23-97af6b281e6c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e8522771-7970-4f3b-8104-b54f2d5eeaaf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ca0add9d-62a0-4fd6-bf0c-76af417c3eac'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('30332425-facc-4b7a-8994-fac5250e18e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bd193df1-d7fc-493d-9108-db84bd027308'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3ff130dc-e66e-4542-980f-6f33adedb3b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('601777d3-d422-4681-914e-c1f3268e1a56'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('akademik', 'AKADEMİK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('332e1be7-771d-4a98-9a14-a0549364f629'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
