# Generated by Django 2.2.5 on 2019-09-23 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0029_auto_20190923_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3364e2f8-146c-40ca-ac13-2b1b62bcb126'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3c0238c2-5915-4037-a29e-54421be20f85'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ad15ae40-eb23-4da0-a8de-6736edf94c29'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('41d871e4-6d01-4bc5-b163-6be7f18f04e5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('24422690-073c-4148-b6ad-fc405927702e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8b36ccbf-909c-44cf-9650-cc0e91e73ce2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e6705f4f-7655-466f-83e8-21888f96e408'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('80d3b8bd-8678-48ed-8119-d80b911f1fe1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('187e090b-e82d-4d42-a76b-9e6c661bea13'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('akademik', 'AKADEMİK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d382e6d6-066f-4494-867c-bb25a1a6d713'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
