# Generated by Django 2.2.5 on 2019-10-01 13:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0039_auto_20191001_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='sumprice',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Toplam fiyat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d6ce2f3f-d98b-4d56-af84-f37fa611f5a2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a8197142-9700-406b-bd0b-12f265d5a63a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3fed9d8c-b256-4fcd-9afa-ef5f355a6ec0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('96c37199-0b23-40e1-aa2e-82f1ee75eb7b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('735bd07a-a412-43f6-87b4-6db3ca480b38'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7ab210e1-3166-4695-a1c1-dc63f473bd39'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f66fbf04-c02d-409b-bfe0-afd1980c794e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('32d436e6-fdda-497c-bcfe-875199077560'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a4965f73-5ec8-4974-bac5-5c445f175df6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('50d5a45e-3d87-443a-97ea-73e713f9d74d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='comName',
            field=models.CharField(max_length=50, verbose_name='Şirket ismi'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='design',
            field=models.ImageField(upload_to='', verbose_name='Üst tasarım'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='design1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Alt tasarım'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E mail'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='Müşteri isim soyisim'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='pieces',
            field=models.CharField(max_length=50, verbose_name='Kaç parça'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Adet fiyat'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Toplam Fiyat'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('969ef60b-6657-4919-a143-5cbd268bc8ca'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Ölçüler'),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c968795f-cd45-4db6-b03a-5442f89e42f9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici1', 'GEMİCİ 1 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('05e53065-aac6-42ec-9aaa-6a5f5248b8fb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
