# Generated by Django 2.2.5 on 2019-10-03 18:58

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0044_auto_20191003_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='designService',
            field=models.CharField(default=django.utils.timezone.now, max_length=5, verbose_name='Tasarım hizmeti verilecek mi?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a2f4a059-d1a0-42ba-83c8-4037b136802b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7e9d9919-62f3-463b-ace6-b4ca772a513f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6f97cc23-a377-4144-b0ba-dbf46bd08180'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c3ee47e8-10bf-4e7e-9ca5-d2d51141a3c6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e72c8429-1201-4461-8ee2-df9605216a3f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a128d469-57e1-4999-8da9-cd9446f57849'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('96319a6f-c7ee-4de0-bebf-123771f93d69'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('080fd011-350d-4094-a17e-e304101c33ff'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8f7cb402-009e-44a7-98ba-4050e23aa59f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d21191dd-de89-4bf7-96a1-1286e1e8f06b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 18, 58, 50, 774521, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('213bc94d-3763-4984-8810-c77fcdd5d0ad'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2c90291e-4ade-4de5-806f-5548a8d03a0d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f181d9a4-707d-46cc-a4b2-773102038b4e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
