# Generated by Django 2.2.5 on 2019-10-09 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0050_auto_20191008_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d900a839-3124-4f31-9273-3ddfebc4c2c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b862d179-d4f3-4ada-b2c4-a3e58da89bc3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('85263156-2b04-467c-b67b-78352e12be79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4eab9036-fd69-483d-b83b-c7a3e2bcd166'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('374616f5-612b-4469-963e-6cb3111dc0e4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0a50b7a9-248e-404c-8017-c495d94e0612'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6df13a1e-0fe7-428d-acb2-0021a52ee769'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('1541f0db-e943-4ce1-a355-4b9b1d117259'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('006fee1c-1e3f-4cad-b8c1-33e7235242c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('772b4f47-6c1a-48a3-85e3-998ff389bc4e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9d813bba-9eb2-4d80-a3a8-c830701a4657'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 10, 2, 35, 261470, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('53a20f38-fedb-4054-a0a0-c0d6c805a4dd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a0f03d22-8d66-46c1-9de5-ca50876a186d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('191e2e95-2ca9-40de-b035-898357a4767f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
