# Generated by Django 2.2.5 on 2019-10-09 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0052_auto_20191009_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajanda',
            name='exp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='akademik',
            name='exp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gemici1',
            name='exp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gemici3',
            name='exp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='masaustu',
            name='exp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('eeb09b15-227c-4186-9e09-380d2ece602d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('981144e6-ced7-4a41-bea1-1995480396c5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c9db5042-7cc8-4c0b-8db0-91ae7c7d0c0f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('16446ca2-a301-400e-a2fb-8fe4fb07a0b0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2479b9cd-9e06-4b69-8da6-35eeaca06a2b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bafb9621-527d-4ab9-9ade-ed09bbd40aa2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0a97de24-82de-4967-8bdc-e80c6e316c7d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('07477cdb-8594-4e48-a101-05c1576757af'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4fae93a2-9ded-4623-b1b3-d5530b81bd32'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('45e452df-4f7b-4140-93e9-a9d746ca3a34'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('cefa0033-9fa0-458b-90b2-72fff9e510a7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 21, 20, 11, 1833, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e97e1bd9-7a5e-44ae-a83d-7de49eb1c795'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('dcd706d1-5577-48a2-8e4e-ca1ddaa8d9a0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('akademik', 'AKADEMİK'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7402ed53-ce68-41e5-b48b-f76f1766cabf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
