# Generated by Django 2.2.5 on 2019-11-04 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0054_auto_20191104_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagramgonderi',
            fields=[
                ('gonderi_id', models.UUIDField(blank=True, default=uuid.UUID('548fac30-3df8-4c8b-9b4f-ab2e2e283680'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=5000, verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2b784149-c948-4d51-946e-3be18055e2ce'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a592948d-5544-4283-9092-6d59f049a436'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('1dca6a2f-7260-4053-91f0-b94e4790d75f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('de6cc83b-8cdb-4f9c-a237-a16445d9f6af'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('96499192-44c2-416f-af39-e95b25122391'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bedd53aa-131f-4472-8579-a0817c7cea6c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e3d75ce2-f759-459b-a6c1-97062f541fa3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7adaa0d2-7ebc-47af-ba0d-3d6da2881c65'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('37e8df4e-b3d8-4e97-9786-6dc01171e616'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b9ba0728-c938-4ec0-99ea-8591694334e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price1000_2000',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (1000-5000 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price100_200',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (100-200 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price2000_5000',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (1000-5000 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price200_500',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (200-500 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price500_1000',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (500-1000 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price50_100',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (50-100 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('085538ba-6d18-4af7-babc-e17d3154e833'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 18, 13, 1, 35561, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('349f1a2a-5c4f-42f1-a8a1-402a3ad8ba80'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('81f6b591-e4d1-402d-80ac-b5b1cc972d33'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 3 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a2f7caa7-da6f-40e1-90c8-0cace38bf11e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
