# Generated by Django 2.2.5 on 2019-11-05 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takvim2020', '0055_auto_20191104_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c780ae15-73b6-4c65-ba58-c3fda6e81a70'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0f75e8c1-74d9-417a-95ee-ed3c77f99ea0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('97fc4d4e-a6c2-48eb-91e2-d3d9eedf7cc6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d6982bd4-c29b-4d9d-b4a1-7bc2c0a03d9f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9923531f-b973-4957-9b8d-0a3d556d85d7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d7eb14d6-7bb5-4848-9482-07e7268a44ad'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('74e963ba-4253-453b-9aba-e35c12a5a043'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e21dcdba-0122-4988-a888-d5406fc28c8a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d1e883b9-d04e-496a-a84e-96d6a828c297'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ab9bcdbd-30ea-4dab-89b8-10628177aec9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2699a727-126c-4d18-a565-81172ceff211'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price1000_2000',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (1000-2000 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price2000_5000',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fiyat (2000-5000 adet için)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('89b7bf82-23a0-406f-9409-429f46db7e19'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 10, 56, 1, 195591, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4e7b478c-ba8b-4412-b55c-68dacfd07be7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e58c3825-5dba-4e05-9304-d4c3460fd71e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('da0ae974-69d4-4129-8ecd-9cf77bcfca79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='gemici2',
            fields=[
                ('product_id', models.UUIDField(blank=True, default=uuid.UUID('1d7b38aa-d04c-4829-8e41-1cfd2eb23b63'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='GEMİCİ 3 Spiral', max_length=50)),
                ('category', models.CharField(choices=[('gemici4', 'GEMİCİ 4'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori')),
                ('exp', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OlcuGemici2', to='takvim2020.size', verbose_name='Ölçü 1 için  boyut - renk - fotoğraglar ')),
            ],
        ),
    ]
