# Generated by Django 2.2.5 on 2019-11-05 11:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takvim2020', '0056_auto_20191105_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b6e44b98-68d3-4b92-884e-df92bbb703a9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3b493ac5-c021-41c8-a6a3-1553b0760a21'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('89ca094f-bc95-4fe9-8bd4-7cc2ae26bc5c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0e4c3e0a-f82e-4928-a276-bf122fded1bb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7ba02794-e195-4a52-b46c-c13b7c69080b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9b9d9810-e647-43a2-ae50-7fa71500d077'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c65d5185-5489-4178-a5bf-95e9c46a026c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9ed6a89c-e28f-4c44-9a4d-d197a497d2aa'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d135d4d7-d6f2-4ddf-a2cb-3fe408371691'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('5593ffed-321a-42c6-a67b-2f861aad32a6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3aa99981-cfad-4135-8bd5-a115e3bd13fe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('19668cd4-c583-4771-b1f8-68388be224df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('43c67b44-a22c-40df-9b9c-78a6f658a9c9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 16, 36, 255910, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('fc256372-7da6-4c73-8174-dd7a06f5fa7b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6b773958-9f10-4525-a5a0-fd0fb4a3fab1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('561820b3-ca2b-43c9-9461-3bb6babfd89e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='gemicieko',
            fields=[
                ('product_id', models.UUIDField(blank=True, default=uuid.UUID('9575c2ae-74d8-4104-9b45-fc9a5d01bb61'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='GEMİCİ 3 Spiral', max_length=50)),
                ('category', models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici4', 'GEMİCİ 4'), ('ajanda', 'AJANDA')], max_length=20, verbose_name='Kategori')),
                ('exp', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('size1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OlcuGemiciEko', to='takvim2020.size', verbose_name='Ölçü 1 için  boyut - renk - fotoğraglar ')),
            ],
        ),
    ]
