# Generated by Django 2.2.5 on 2019-11-14 21:56

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0058_auto_20191112_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemici1',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuc',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('92c2fb6c-12bf-4e2d-a6ea-883ac333e304'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('320d32ac-24f4-4c5f-ba6a-e95cf73489e5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b683a3b1-ae52-4dfb-b333-2c5a0ce12082'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('68d19bc3-474a-406e-bd47-4911e9184180'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('cb4f6219-a432-41bd-a063-ac2f2558943b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('149910c5-c6e7-44dc-89f6-14d40f844f76'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('be2f71a9-9ea3-48b4-ba64-424c625a567a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('316447cc-2c91-4eb1-926c-a3109376993f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('fd7d2c56-a2f6-4142-bf9f-98f47da1c145'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9eef1feb-c74f-459f-b3a4-cae78bf26fe1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c71605cd-5594-4a0a-b4c2-4a98c7fd53e2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('59fc4802-3a59-478c-9861-28a2b6336787'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('97d4684c-6929-4d87-8828-f0f27339352a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('5f4edd7c-f696-4565-90d5-e83ee6560355'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 21, 55, 51, 482016, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b93e0311-8bde-4b00-9cf3-965cf58e3143'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('00a4500c-4c31-448b-b559-025703680a0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e225d60b-64fb-4c73-9616-3a80211dc63d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
