# Generated by Django 2.2.5 on 2019-11-14 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0059_auto_20191114_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('60c6e4ae-2a1c-4c32-b5f4-4d9aee711c20'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d44a3bd3-edaa-440c-bc8a-9ddc18511db1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2fd89967-21b4-469e-b782-f9b8489b41f2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2634fd6a-350b-4179-beef-e00dbc112a6b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('5f42af44-6bc0-489c-95d2-199353dd846d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('904b7dcb-f662-473b-b170-f7d6b72599ca'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b4b519bc-89e8-493f-8917-cec7ce6987c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d1df96da-6b71-4919-a963-4231d80fd85a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('17f4b4a2-1137-433b-9d82-e65974ea795a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a93dbb7d-1597-41a2-b356-8fc6a276c61c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6543a1b5-3d2a-4a90-9430-d7e24df4829b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b185fa94-e1bb-4373-bafb-68dcc4b35d54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ad930f51-f2bb-4f60-a59f-4e9fe3357514'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('83ec6e8f-913f-4ede-8109-91aec442f38c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 22, 2, 35, 213146, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('05eff093-7491-4e42-b32c-f63fdbd2ce09'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b173d6c1-eb2d-4721-a32b-8a0b3aa71896'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemici3', 'GEMİCİ 3 Spiral'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('ajanda', 'AJANDA'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 22, 2, 35, 212734, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a32e1cbd-b058-426e-8a14-b2ac5682dc45'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
