# Generated by Django 2.2.5 on 2019-11-15 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0061_auto_20191115_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('56bdff82-ed4f-4744-a1d0-d3822b7d93fd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('df5887a8-205d-47a5-9b72-7e9078fe6b81'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bd81d5a2-9db5-4d40-95d7-e53b980d5b8d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('5d13ae2c-9e42-49b0-8fc6-608471e19c59'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7e47b936-4828-40b3-8193-cec6e0a94d96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9b36465a-5a25-4267-a7fe-a5753d4770c7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e8c17743-8dba-41b4-8153-d75d91a36258'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('750930e0-deaf-4985-9f74-af3dc0fe660b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('13938dec-7a98-4986-8676-c0f77f4a3062'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c7af3d1c-c965-4d39-b3e8-30dad024743c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f951461c-8f8a-4430-a276-2062fe069d96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ae9ad5a6-a870-4e67-8909-7a02f39504c6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='created',
            field=models.DateTimeField(blank=True, default=1573826944.9808128, null=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('81572426-7201-4286-af06-d6759cbb2222'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d3e2c16f-0766-4f72-94de-1752a6e500f8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 14, 9, 4, 988949, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7cbd5128-ad3b-4305-8c36-760e8f26c8c1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9b58aef5-ed56-4678-8d86-07fcb5fa2369'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('ajanda', 'AJANDA'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.DateTimeField(blank=True, default=1573826944.9884613, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7fe13f74-1ec3-4185-ae1a-1e35f625f240'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
