# Generated by Django 2.2.5 on 2019-11-15 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0067_auto_20191115_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('648a2f2e-84b7-471a-9c22-f7e5a3e9aab7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a847197d-1991-42b1-beb3-dbee3805fb32'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c27e20c8-59bf-4473-9edc-370ccaf9cc0e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('469198bf-23cd-42e2-832c-897793f929a1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('25af1f5e-7234-4f4d-88b5-5de335aa7f3a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a5c0f768-b3e8-481d-a399-757a7875ab97'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('fc5b7a5c-0e79-4f35-a269-f84d1a9ae50d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('204cdaaa-b4a8-4791-af7b-4e56d99cf37b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ecb827e8-3fb8-4621-b879-03b51b528e35'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a03866cc-73f9-4c64-9a65-288f8f238eef'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('13f2e001-5854-4b8c-8b12-0b6214177833'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e843022c-0843-4392-b1b2-a5f6ff606e96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('76cbd732-f330-478a-84b9-c2c1d7a284cf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('529183c9-f023-4095-99dd-aa2eed615c51'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 21, 32, 28, 118264, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8a60ff73-acac-4dfc-b7a4-ec24ac17a7f8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b55d8d93-537d-4ae9-b6c3-b9cf6e5cfa71'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral'), ('masaustu', 'MASAUSTU')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.FloatField(default='1573853548.1176953', max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('efc211da-0f99-41eb-a707-c15a00d1917b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
