# Generated by Django 2.2.5 on 2019-11-15 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0069_auto_20191115_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8d4277f8-b61e-4c25-a9ea-933ae6872a94'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('32cb2a0c-7757-4df1-952e-fcbd58a6d5e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('f1ffc425-797f-491e-9856-c2f18bcb449d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('956aa76e-a691-4ed7-b6b5-05647bccd661'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('07f36376-842c-4c4b-99da-50380ebea9d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('16b8552e-051e-46f3-b96e-f3bdb6b12b6b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d8111099-381f-4cdd-9233-94014346b6d9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8f91e80a-37de-438c-bce1-cbf6655f554b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('327ac7c9-389b-44bf-9dc7-707e6dc6117d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('ebbcf847-6070-4a9d-ac19-5d4e404eba8b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('85c0ceae-f1e4-4d4d-9039-8ff66e7f2d02'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c8898a8e-036b-4c49-8f2a-41463188fc58'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('73c6fc28-0a26-416a-b613-d32ff0a22a52'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='ordering',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4c45b092-f986-42a1-b70f-3ad67b92922f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 21, 33, 19, 156178, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('298a20b2-5fc2-445e-88d1-047f5d67b74b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('25505406-4ff8-49ec-8b1c-97b0e0bad965'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemici1', 'GEMİCİ 1 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created',
            field=models.FloatField(default='1573853599.155615', max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('797ac0b0-b34e-4c08-8a8e-456221b96b26'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
