# Generated by Django 2.2.5 on 2019-11-25 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0071_auto_20191116_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='created',
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('384aea7b-6464-43e1-bd89-1204fbc27ceb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('61febb6f-d040-4ed5-8abe-ddf24058f1f7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('426301d4-08fa-4e52-b9bf-15259beeaefb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('37b7ef9b-ee69-46f9-bd72-2e0be6eea970'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('193e7d5a-ddd4-4210-86e1-dce781d8a908'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c38b43b3-d449-4997-a2b5-164ea42ef3d7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3377b4d8-7136-41f2-bf45-88209368f030'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('caa7437f-c076-4488-99aa-7a9090261a85'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2aeef85b-d2f7-48e6-9402-788a333d1726'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7450a0ea-8f8c-461f-8734-e8c2a1ecbe43'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a56357b5-8c82-48d3-983b-f78b25a36e5e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('94182d05-af97-45e7-b25b-e5444beebbc9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('33d769aa-6380-4328-b6c3-e468d3ab4a3d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('940abbd4-5b57-4a81-b735-c38d3ac7ea62'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 21, 18, 51, 93278, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('d3f99d1b-e83f-4ce2-bc31-c78e98a5d8b3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('dbe9fd93-8df6-4c3d-87cf-48d4d42b8154'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemici2', 'GEMİCİ 2 Spiral'), ('gemicieko', 'GEMİCİ EKO'), ('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('683bf3b3-71a4-4983-a7b1-23176638e68c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
