# Generated by Django 2.2.5 on 2019-11-25 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0072_auto_20191125_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('33c439bd-d27f-4aab-8730-cd4b340be9e2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('25089705-1a2c-4ed7-b4e2-872789467436'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b14758e5-7831-42e7-bb65-33a13ffb2d9e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6140d09f-a5c6-420c-a9f7-7b92be26b2e9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2999ecee-b426-4f33-a9f7-cb77eede9ad8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('0106ae16-6acd-4785-89a9-de6d0bd0fbd4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7923de19-c6f6-427d-b1e8-2106712dea7c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('25336402-e1b5-4c4c-9eb8-7a730e8538dd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('77180333-cc18-481e-964e-3176a7f269b1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7adbbb8a-3b97-4551-bb73-4d35796e364d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('77c442af-b845-412d-8b08-654d1fa8c763'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b7fa6d59-2c87-42e3-898d-e1f4396d0708'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b8317db9-2ebc-4c1e-af83-cab681ba0d65'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('056d1c6e-1aad-4b78-9f27-d9ac422fcd38'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 21, 19, 5, 828359, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('12b8ff7d-47c9-4cd2-a8d6-25f111d1c3b9'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('c00e0750-3398-480c-a85d-0c0750a5e71d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('ajanda', 'AJANDA'), ('masaustu', 'MASAUSTU'), ('gemicieko', 'GEMİCİ EKO'), ('gemici1', 'GEMİCİ 1 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici2', 'GEMİCİ 2 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('18dd51c1-951e-48fb-bd62-281ce3970aa0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
