# Generated by Django 2.2.5 on 2019-11-26 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takvim2020', '0073_auto_20191125_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajanda',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ajanda',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('9e40d247-cb5d-4e2d-98eb-c718d2246030'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='akademik',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b47086da-3eac-46b6-bc96-ca5600567fa5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7c8505c1-2540-4a66-a144-abd0fe87cf7a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color2_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('64e263a0-ba39-45a6-96de-ffb5055b5b72'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='model',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='colorname',
            name='color_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e02f7327-d964-498f-8a5f-ab6adb8a6312'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('658ce136-7e5f-4876-9b95-b4dbc58493c4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici1',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('3c117517-0adb-49fd-b818-b9f8ac8c7aee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici2',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('2d48a266-9611-451e-bda0-c13937302220'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemici3',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('4f48b2ba-d438-4987-b070-aaf95a0e564c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='gemicieko',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b8e74789-bdd2-4748-91d2-9ed7bebdcff6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramgonderi',
            name='gonderi_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('e1adb7c4-e279-4523-b01f-40b461afb0be'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='masaustu',
            name='product_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('a321f322-2e35-48f2-91da-40d41e90f88a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menuItem',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='menuc',
            name='menu_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('7bc63277-175b-427a-bc58-250756dfaf18'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='model',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('02afa444-8d0c-4be0-93a9-d1a179293bb4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 8, 23, 44, 102121, tzinfo=utc), verbose_name='Siparis zamanı'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='product_id',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='siparis_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('dd414739-9670-4bda-a9c9-c7ad5713424e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bebef198-38c9-4d6f-b5a8-d7d7ca722130'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.CharField(choices=[('gemicieko', 'GEMİCİ EKO'), ('masaustu', 'MASAUSTU'), ('ajanda', 'AJANDA'), ('gemici2', 'GEMİCİ 2 Spiral'), ('gemici3', 'GEMİCİ 3 Spiral'), ('gemici1', 'GEMİCİ 1 Spiral')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=models.UUIDField(blank=True, default=uuid.UUID('5931cf44-2cb3-4806-8f82-3f1d933c114f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
